# Latihan Data Cleaning & Preprocessing

## 1. Import Library

In [21]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [22]:
print(sns.get_dataset_names())

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']

## 2. Load Dataset

In [23]:
df = sns.load_dataset("titanic")

In [24]:
display(df.head())

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [26]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

## 3. Data Cleaning & Preprocessing

### 3.1 Data Cleaning

In [27]:
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [28]:
df["age"] = df["age"].fillna(df["age"].median())

In [29]:
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [30]:
df.drop("deck", axis=1, inplace=True)

In [31]:
print(df.isnull().sum())

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

In [32]:
df["embarked"] = df["embarked"].fillna(df["embarked"].mode()[0])
df["embark_town"] = df["embark_town"].fillna(df["embark_town"].mode()[0])

In [33]:
print(df.isnull().sum())

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [34]:
print(df.duplicated().sum())

116

In [35]:
df.drop_duplicates(inplace=True)

In [36]:
print(df.duplicated().sum())

0

### 3.2 Data Preprocessing

#### Normalisasi dengan MinMaxScaler

In [37]:
scaler_minmax = MinMaxScaler()

df["fare_normalized"] = scaler_minmax.fit_transform(df[["fare"]])
print(df[["fare", "fare_normalized"]].head())

      fare  fare_normalized
0   7.2500         0.014151
1  71.2833         0.139136
2   7.9250         0.015469
3  53.1000         0.103644
4   8.0500         0.015713

#### Standarisasi dengan StandardScaler

In [38]:
scaler_standard = StandardScaler()

df["fare_standarized"] = scaler_standard.fit_transform(df[["fare"]])
print(df[["fare", "fare_standarized"]].head())

      fare  fare_standarized
0   7.2500         -0.527515
1  71.2833          0.695086
2   7.9250         -0.514627
3  53.1000          0.347909
4   8.0500         -0.512240

In [39]:
df.to_csv("titanic_clean.csv", index=False)

# Scraping Data CNN

In [40]:
import pandas as pd
import time
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By

In [41]:
# Fungsi Mencari URL Pencarian

def get_url(page):
    if page == 1:
        return "https://www.cnnindonesia.com/search?query=IHSG"
    else:
        return f"https://www.cnnindonesia.com/search?query=IHSG&page={page}"

In [42]:
# Fungsi menyimppan data ke CSV
def save_to_csv(titles):
 
    df = pd.DataFrame(titles, columns=['judul'])
    df.to_csv('judul_berita_ihsg.csv', index=False,encoding='utf-8-sig')
    print(f'Sukses simpan {len(df)} judul berita ')

In [43]:
# Fungsi Scraping Judul Berita

def scrape_titles():
    options = Options()
    options.add_argument('--disable-gpu')
    driver = webdriver.Chrome(options=options)
    titles = []

    for page in range(1, 11):
        url = get_url(page)
        print(f'Scraping {url}')

        driver.get(url)
        time.sleep(2) # Tunggu halaman selesai render

        try:
            h2_elements = driver.find_elements(By.CLASS_NAME,'text-cnn_black_light')
            if not h2_elements:
                print(f'Tidak ada judul ditemukan di halaman{page}.')
                break
            for h2 in h2_elements:
                titles.append(h2.text)
        except Exception as e:
                print(f'Error di halaman {page}: {e}')
                continue
    driver.quit()
    return titles


hasil_judul = scrape_titles()
save_to_csv(hasil_judul)

Scraping https://www.cnnindonesia.com/search?query=IHSG
Scraping https://www.cnnindonesia.com/search?query=IHSG&page=2
Scraping https://www.cnnindonesia.com/search?query=IHSG&page=3
Scraping https://www.cnnindonesia.com/search?query=IHSG&page=4
Scraping https://www.cnnindonesia.com/search?query=IHSG&page=5
Scraping https://www.cnnindonesia.com/search?query=IHSG&page=6
Scraping https://www.cnnindonesia.com/search?query=IHSG&page=7
Scraping https://www.cnnindonesia.com/search?query=IHSG&page=8
Scraping https://www.cnnindonesia.com/search?query=IHSG&page=9
Scraping https://www.cnnindonesia.com/search?query=IHSG&page=10
Sukses simpan 100 judul berita