# Feature Engineering & EDA
Feature Engineering adalah proses mengubah data mentah menjadi fitur (kolom) yang lebih
informatif dan sesuai untuk model machine learning, seringkali dengan memanfaatkan
pengetahuan domain untuk mengekstrak sinyal yang relevan. 

Sebagai ilustrasi, proses ini dapat
diibaratkan seperti seorang koki yang menyiapkan bahan mentah (memotong, membumbui)
sebelum memasak agar hasil akhirnya maksimal. Praktik ini sangat erat kaitannya dengan
Exploratory Data Analysis (EDA), yaitu proses investigasi awal pada dataset untuk
menemukan pola, mendeteksi anomali, dan merangkum karakteristik utama melalui statistik
dan visualisasi. 

Keduanya saling terkait erat: EDA memberikan wawasan untuk melakukan
feature engineering, dan fitur baru yang dibuat kemudian dianalisis kembali melalui EDA.

### 1.1 Install Library

In [ ]:
# pip install pandas seaborn scikit-learn matplotlib

### 1.2. Import Library yang Dibutuhkan

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder
from sklearn.ensemble import RandomForestClassifier

### 1.3. Mempersiapkan Dataset
Pertemuan ini menggunakan dataset dari seaborn, yaitu dataset "penguins".
- #### 1.3.1 Import Dataset

In [2]:
df = sns.load_dataset('penguins')
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

- #### 1.3.2 Melihat Informasi Dataset

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 24.9 KB

### 1.4. Menangani Missing Values
Row yang memiliki data null akan dihapus.

In [4]:
df.dropna(inplace=True)
print(f"Jumlah Baris setelah dihapus: {len(df)}")

Jumlah Baris setelah dihapus: 333

## 2. Encoding Data Kategorikal
Sebagian besar algoritma machine learning memerlukan input berupa data numerik. Oleh
karena itu, data kategorikal (teks) harus diubah menjadi representasi angka melalui proses yang
disebut encoding. Terdapat dua pendekatan utama:

#### 2.1. Label Encoding & Ordinal Encoding

Secara umum, Label Encoding adalah metode yang mengubah setiap kategori unik
menjadi sebuah nilai integer (misal: 'Merah' => 0, 'Biru' = >1). Namun, pendekatan ini
harus digunakan dengan hati-hati pada fitur, karena penetapan angka yang otomatis
(misalnya berdasarkan abjad) dapat menciptakan urutan yang tidak bermakna dan
menyesatkan model.

Untuk data yang memiliki tingkatan jelas (data ordinal), metode yang lebih tepat
adalah Ordinal Encoding. Metode ini memungkinkan kita untuk secara eksplisit
mendefinisikan urutan angkanya (contoh: 'Kecil' => 0, 'Sedang' => 1, 'Besar' => 2)
sehingga representasi numeriknya akurat dan sesuai dengan makna data.

#### Kolom sex memiliki dua kategori, sehingga cocok untuk Label Encoding. 
LabelEncoder mengubah 'Female' menjadi 0 dan 'Male' menjadi 1.

In [5]:
le = LabelEncoder()
df['sex_encoded'] = le.fit_transform(df['sex'])
print(df[['sex', 'sex_encoded']].head())

      sex  sex_encoded
0    Male            1
1  Female            0
2  Female            0
4  Female            0
5    Male            1

#### 2.2. One-Hot Encoding

Metode ini mebuat kolom biner (bernilai 0 atau 1) baru untuk setiap kategori unik.
Pendekatan ini ideal untuk data nominal, yaitu data yang tidak memiliki urutan intrinsik
(misalnya: 'warna', 'kota'). Tujuannya adalah untuk menghindari asumsi adanya urutan
yang salah pada data, meskipun dapat menambah jumlah kolom secara signifikan jika
kategori sangat banyak.

#### Kolom island adalah fitur nominal. Terapkan One-Hot Encoding pada fitur ini.

In [6]:
island_one_hot = pd.get_dummies(df['island'], prefix='island')
df = df.join(island_one_hot)
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,sex_encoded,island_Biscoe,island_Dream,island_Torgersen
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,1,False,False,True
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,0,False,False,True
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,0,False,False,True
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,0,False,False,True
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,1,False,False,True

In [7]:
avg_mass =
df.groupby('species')['body_mass_g'].mean().sort_values()
print("Urutan spesies berdasarkan massa rata-rata:")
print(avg_mass)
species_order = avg_mass.index.tolist()
ordinal_encoder = OrdinalEncoder(categories=[species_order])
df['species_ordinal'] =
ordinal_encoder.fit_transform(df[['species']])
print(df[['species', 'species_ordinal']].sample(10))

SyntaxError: invalid syntax (371568391.py, line 1)

## 3. Binning (Discretization)
Binning, atau dikenal juga sebagai discretization, adalah sebuah teknik preprocessing data
untuk mentransformasi fitur numerik kontinu menjadi fitur kategorikal diskrit. 

Proses ini dilakukan dengan membagi rentang nilai dari sebuah fitur ke dalam sejumlah interval atau
"bins", kemudian menetapkan setiap titik data ke dalam bin yang sesuai. Sebagai contoh, fitur
'harga' dapat dikelompokkan ke dalam kategori 'Rendah', 'Menengah', dan 'Tinggi'.

Tujuan dari proses ini adalah untuk menyederhanakan data, meningkatkan robustisitas
model terhadap nilai ekstrem (outlier), dan memfasilitasi algoritma machine learning dalam
menangkap hubungan non-linear antar variabel.

## 4. Feature Selection
Feature Selection adalah proses seleksi sistematis untuk memilih subset fitur (variabel atau
kolom) yang paling relevan dari sebuah dataset. 

Tujuan utamanya bukan sekadar mengurangi
jumlah dimensi data, melainkan untuk meningkatkan performa prediksi model, mengurangi
risiko overfitting (ketika model terlalu hafal data training), mempercepat waktu komputasi,
serta meningkatkan interpretabilitas model.

Secara umum, metode feature selection dapat diklasifikasikan ke dalam tiga kategori utama:
- **Metode Filter** mengevaluasi relevansi fitur berdasarkan karakteristik statistik data, terlepas dari
model machine learning yang akan digunakan.
- **Metode Wrapper** menggunakan performa sebuah model machine learning spesifik untuk
mengevaluasi dan memilih subset fitur terbaik.
- **Metode Embedded** mengintegrasikan proses seleksi fitur langsung ke dalam algoritma saat
model sedang dilatih (training).

## 5. Exploratory Data Analysis (EDA) dan Visualisasi Distribusi
Exploratory Data Analysis (EDA) adalah pendekatan investigasi untuk menganalisis dan
merangkum sebuah dataset. 

Tujuan utamanya adalah untuk menemukan pola, mendeteksi
anomali, menguji hipotesis, dan mengidentifikasi karakteristik utama data, seringkali dengan
bantuan statistik deskriptif dan representasi grafis.